language: c
script: cd src && make

matrix:
  include:

  # Linux / gcc
  - compiler: gcc

  # Linux / MinGW 32 bit
  - compiler: g++-mingw-w64-i686
    addons: {apt: {packages: [g++-mingw-w64-i686]}}
    script: cd windows && make

  # Linux / MinGW 64 bit
  - compiler: g++-mingw-w64-x86-64
    addons: {apt: {packages: [g++-mingw-w64-x86-64]}}
    script: cd windows && make

  ## Mac (disabled for now, need to provision ncursesw)
  #- compiler: clang
  #  os: osx
  #  script: cd src && make CC=clang MACOSX=-DMACOSX LINUX=
