language: c
script: cd src && make

matrix:
  include:

  # Linux / gcc
  - compiler: gcc

  ## Mac (disabled for now, need to provision ncursesw)
  #- compiler: clang
  #  os: osx
  #  script: cd src && make CC=clang MACOSX=-DMACOSX LINUX=
